Merge `test-branch` to `development`  branch
o-rashad/TodoApp-Js pull request #2
Opened 2021-08-27 10:56 UTC by od-c0d3r

- Implement `Jest` node package to test JavaScript `classes`, `modules` and functions.

2021-08-27 11:21 UTC, whiz25 requested changes
## Changes required 🙏🏿 🙏🏿 🙏🏿 
Nice work on the testing. You did well. 
### changes 🔕 🔕 🔕 
- check comments for suggestions

### Martin Afani
#### Slack: whiz25

2021-08-27 11:21 UTC, whiz25 commented on __tests__/models/project.test.js
> +    expect(actual.addTodo(todo)).toBe(1);
Add tests for `saveToLocal`, `deleteProject`, and `displayProjects` functions. All functions have to be tested.

2021-08-27 11:21 UTC, whiz25 commented on __tests__/models/todo.test.js
> +describe('Todo Class tests suite', () => {
Add tests for `showTodos`, `saveTodo`, `deleteTodo` and other functions. You may need to restructure your code for easier testing. You mixed is logic with Dom logic in common.js. Am guessing this is why you could not test those functions. 
The best thing to do is to move those functions to the to-do.js module so you can test easily.

2021-08-31 09:25 UTC, od-c0d3r commented on __tests__/models/todo.test.js
> +describe('Todo Class tests suite', () => {
I have done testing all the testable functions available 
however I couldn't find those functions `saveTodo`, `deleteTodo`

Please make sure those exist in my project. 😃

2021-08-31 10:22 UTC, rindrajosia requested changes
Hi <STUDENT_MENTION>, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️

- [ ] All functions should be tested:
You can use the --coverage flag to get information:
![1](https://user-images.githubusercontent.com/58552748/131484616-9431c4a5-632a-4d1f-9cf7-6261327345e0.png)
As you can see in this screenshot for example, 50% of functions inside project.js are tested,...

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ ] Always remember to add false test cases to your project.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-08-31 10:22 UTC, rindrajosia commented on src/project.js
> +  static saveToLocal(project) {
- [ ] [REQUIRED] All functions should be tested

2021-08-31 10:22 UTC, rindrajosia commented on src/project.js
>    static projectsEvents = () => {
- [ ] All functions should be tested

2021-08-31 13:22 UTC, mke2111 approved these changes
### Hi @od-c0d3r, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉** 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------

2021-08-31 13:29 UTC, od-c0d3r commented
Thank you @whiz25 , @rindrajosia , @mke2111 for the reviews ☺️👍🏼

2021-08-31 13:30 UTC, merged